ALTER TYPE "ProcedureStatus" ADD VALUE IF NOT EXISTS 'NOT_APPLICABLE';
ALTER TABLE "Evaluation" ADD COLUMN "resolutionG" TEXT;
ALTER TABLE "Instrument" ADD COLUMN "serialNo" TEXT;
ALTER TABLE "Instrument" ADD COLUMN "minG" TEXT;
ALTER TABLE "Instrument" ADD COLUMN "unomV" TEXT;
ALTER TABLE "Instrument" ADD COLUMN "specs" TEXT;
ALTER TYPE "ProcedureKey" ADD VALUE IF NOT EXISTS 'ZERO_SETTING';
ALTER TYPE "ProcedureKey" ADD VALUE IF NOT EXISTS 'TARE_SETTING';
ALTER TYPE "ProcedureKey" ADD VALUE IF NOT EXISTS 'STATIC_TEMP';
